### ISSUE TITLE
I wonder how to convert DeepLesion datatype to VOC datatype?

### ISSUE THREAD

**Issue by suyouooooo** [anir16293/Deep-Lesion#2]
Here I noticed that only voc2coco.py is available, however, I cannot use the DeepLesion dataset in the VOC annotations. So, I wonder how to convert DeepLesion datatype to VOC datatype?

**Comment by Ryoo72** [comment]
Hi, did you solve the problem? I'm having the same problem.

**Comment by ZhenxiongTang** [comment]
> 您好，您解决了问题吗？我遇到了同样的问题。您好，您解决了问题吗？我遇到了同样的问题。
您好，这个问题你解决了吗
